swagger: "2.0"
info: 
  description: "API Rest, projeto Gama Academy"
  version: "1.0.0"
  title: "Swagger - JobsNet"
  contact:
    email: "caelialmeida@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "jobsnet-cadastro-por-caeli.herokuapp.com"
basePath: "/v1"
tags:
- name: "formulario"
  description: "Operações com o formulário"
- name: "HTML"
  description: "Páginas"
schemes:
- "https"
- "http"
paths:
  /formulario:
    post:
      tags:
      - "formulario"
      summary: "Adiciona uma entrada no formulário"
      parameters:
      - in: "body"
        name: "body"
        description: "Dados do formulário"
        required: true
        schema:
          $ref: "#/definitions/Formulario"
      responses:
        "200":
          description: "Sucesso"
        "404":
          description: "Não encontrado"
  /:
    get:
      tags:
        - "HTML"
      summary: "Página inicial"
      responses:
        "200":
          description: "sucesso"

definitions:
  Formulario:
    type: "object"
    required:
      - "nome"
      - "Cargo"
      - "Dia"
      - "Mes"
      - "Ano"
      - "CEP"
      - "Bairro"
      - "Endereco"
      - "Cidade"
      - "Estado"
      - "Celular"
      - "email"
      - "CPF"
      - "Habilitacao"
      - "Veiculo"
    properties:
      nome:
        type: "string"
        description: "Nome completo"
      Cargo:
        type: "string"
      Dia:
        type: "string"
        enum: 
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "8"
          - "9"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"
          - "19"
          - "20"
          - "21"
          - "22"
          - "23"
          - "24"
          - "25"
          - "26"
          - "27"
          - "28"
          - "29"
          - "30"
          - "31"
      Mes: 
        type: "string"
        enum:
          - "Janeiro"
          - "Fevereiro"
          - "Março"
          - "Abril"
          - "Maio"
          - "Junho"
          - "Julho"
          - "Agosto"
          - "Setembro"
          - "Outubro"
          - "Novembro"
          - "Dezembro"
      Ano:
        type: "string"
        enum:
          - "1990"
          - "1991"
          - "1992"
          - "1993"
          - "1994"
          - "1995"
          - "1996"
          - "1997"
          - "1998"
          - "1999"
          - "2000"
          - "2001"
          - "2002"
          - "2003"
          - "2004"
      estadocivil:
        type: "string"
        enum:
          - "casado(a)"
          - "solteiro(a)"
          - "viúvo(a)"
          - "divorciado(a)"
      sexo:
        type: "string"
        enum:
          - "Masculino"
          - "Feminino"
          - "Não-binário"
      CEP:
        type: "string"
      Bairro:
        type: "string"
      Endereco:
        type: "string"
      Cidade: 
        type: "string"
      Estado: 
        type: "string"
      Celular:
        type: "string"
      Telefone:
        type: "string"
      Contato:
        type: "string"
      email:
        type: "string"
      Identidade:
        type: "string"
      CPF:
        type: "string"
      Habilitacao:
        type: "string"
        enum:
          - "sim"
          - "não"
      Veiculo:
        type: "string"
        enum:
          - "Sim"
          - "Não"
